media: uploads
content:
  - name: posts
    label: Blog
    type: collection
    path: _posts
    icon: rss
    fields:
      - name: title
        label: Title
        required: true
        type: text
        options:
          rows: 1
      - name: body
        label: Body
        required: true
        type: rich-text
        
    