media: uploads
content:
  - name: posts
    label: Blog
    type: collection
    path: _posts
    icon: rss
    fields:
      - name: layout
        hidden: true
        type: string
        default: "post"
      - name: title
        label: Title
        required: true
        type: string
      - name: body
        label: Body
        required: true
        type: rich-text
      - name: excerpt
        label: Excerpt
        description: >-
          A short description shown in search engines. If left blank, the website will try to generate one based on the first paragraph.
        type: text
        required: false
        
    