media: uploads
content:
  - name: posts
    label: Blog
    type: collection
    path: _posts
    icon: rss
    fields:
      - name: layout
        hidden: true
        type: string
        default: "post"
      - name: title
        label: Title
        required: true
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
        description: >-
          The publication date for this post.
      - name: author
        label: Author
        type: select
        default: casa
        options:
          values:
            - value: casa
              label: A Casa
            - value: ana
              label: Ana Luíza Azevedo
            - value: giba
              label: Giba Assis Brasil
            - value: jorge
              label: Jorge Furtado
            - value: nora
              label: Nora Goulart
      - name: body
        label: Body
        required: true
        type: rich-text
      - name: excerpt
        label: Excerpt
        description: >-
          A short description shown in search engines. If left blank, the website will try to generate one based on the first paragraph.
        type: text
        required: false
        
    