# https://www.netlifycms.org/docs/configuration-options/
backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: main # Branch to update (master by default)
locale: pt
# local_backend: true
media_folder: "uploads"
publish_mode: editorial_workflow
collections:
  - name: banner
    label: Banners
    label_singular: Banner
    folder: _banners
    sort: "date:desc"
    create: true
    delete: true
    publish: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    description: >-
      Banners exibidos no início e no fim da página inicial. Apenas os dois banners mais recentes serão exibidos.
    fields:
      - label: Data de ativação
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss"
        required: true
      - label: Imagem
        name: image
        widget: image
        allow_multiple: false
        required: true
      - label: Título
        name: title
        widget: string
      - label: Conteúdo
        name: body
        widget: markdown
      - label: URL de destino
        name: link
        widget: string
        pattern:
          [
            '/[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+.~#?&//=]*)?/gi',
            "Precisa ser uma URL",
          ]
        required: true
  - name: post
    label: Posts
    label_singular: Post
    folder: _posts
    sort: "date:desc"
    create: true
    delete: true
    extension: md
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/blog/{{year}}-{{month}}-{{day}}-{{slug}}/"
    summary: >-
      {{title}} ({{day}}/{{month}}/{{year}})
    description: >-
      Posts exibidos no Blog, com atribuição de autor, listas de tags e arquivos específicos.
    sortable_fields:
      - title
      - date
    view_filters:
      - label: "Posts da Ana"
        field: author
        pattern: "ana"
      - label: "Posts do Giba"
        field: author
        pattern: "giba"
      - label: "Posts do Jorge"
        field: author
        pattern: "jorge"
      - label: "Posts da Nora"
        field: author
        pattern: "nora"
    view_groups:
      - label: Rascunhos
        field: draft
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: "post"
      - label: Título
        name: title
        widget: string
      - label: Conteúdo
        name: body
        widget: markdown
      - label: Resumo
        name: excerpt
        widget: text
        required: false
        hint: >-
          Exibido na lista de posts do blog. Se deixar em branco, o site tentará gerar um resumo automaticamente a partir do primeiro parágrafo do post. Use até 240 caracteres para exibir o resumo inteiro.
      - label: Autor
        name: author
        widget: select
        options:
          - label: A Casa
            value: casa
          - label: Ana Luíza Azevedo
            value: ana
          - label: Giba Assis Brasil
            value: giba
          - label: Jorge Furtado
            value: jorge
          - label: Nora Goulart
            value: nora
      - label: Data
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss"
      - label: Tags
        name: tags
        widget: list
        required: false
        hint: >-
          Uma lista de tópicos separados por vírgulas. Se adicionadas, a notícia aperecerá na página de posts com essa tag.
      - label: Caminho original
        name: original_path
        widget: string
        required: false
        hint: >-
          O caminho original desse conteúdo no site antigo. Útil para criarmos um redirecionamento automático e evitarmos links quebrados no site.
  - name: news
    label: Notícias
    label_singular: Notícia
    description: >-
      As notícias são posts exibidos sem atribuição de autor na página de Notícias da Casa.
    folder: _news
    sort: "date:desc"
    create: true
    delete: true
    summary: >-
      {{title}} ({{day}}/{{month}}/{{year}})
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/noticias/{{year}}-{{month}}-{{day}}-{{slug}}/"
    view_groups:
      - label: Rascunhos
        field: draft
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Título
        name: title
        widget: string
      - label: Conteúdo
        name: body
        widget: markdown
      - label: Data
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss"
      - label: Tags
        name: tags
        widget: list
        required: false
        hint: >-
          Uma lista de tópicos separados por vírgulas. Se adicionadas, a notícia aperecerá na página de posts com essa tag.
      - label: Caminho original
        name: original_path
        widget: string
        required: false
        hint: >-
          O caminho original desse conteúdo no site antigo. Útil para criarmos um redirecionamento automático e evitarmos links quebrados no site.
  - name: essays
    label: Textos
    label_singular: Texto
    folder: _essays
    sort: "date:desc"
    create: true
    delete: true
    summary: >-
      {{title}} ({{day}}/{{month}}/{{year}})
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/textos/{{year}}-{{month}}-{{day}}-{{slug}}/"
    description: >-
      Textos são posts exibidos na página de Textos, com sua própria listagem e organização.
    view_groups:
      - label: Rascunhos
        field: draft
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Título
        name: title
        widget: string
      - label: Conteúdo
        name: body
        widget: markdown
      - label: Autor
        name: author
        widget: hidden
        default: casa
      - label: Date
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss"
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Caminho original
        name: original_path
        widget: string
        required: false
        hint: >-
          O caminho original desse conteúdo no site antigo. Útil para criarmos um redirecionamento automático e evitarmos links quebrados no site.
  - name: projects
    label: Filmes
    label_singular: Filme
    folder: _projects
    sort: "title:desc"
    create: true
    delete: true
    slug: "{{slug}}"
    preview_path: "/filmes/{{slug}}"
    view_filters:
    - label: "Longas"
      field: category
      pattern: "Longas-metragens"
    - label: "Coproduções"
      field: category
      pattern: "Coproduções"
    - label: "Médias"
      field: category
      pattern: "Médias-metragens"
    - label: "Curtas"
      field: category
      pattern: "Curtas-metragens"
    - label: "Séries"
      field: category
      pattern: "Séries"
    - label: "Origens"
      field: category
      pattern: "Origens"
    - label: "Distribuição"
      field: category
      pattern: "Distribuição"
    - label: "Coleções"
      field: category
      pattern: "Coleções"
    - label: "Projetos"
      field: category
      pattern: "Projetos"
    description: >-
      Os projetos ou os filmes. Dependendo da categoria, eles são exibidos em sua lista respectiva.
    fields:
      - label: Layout
        name: layout
        widget: hidden
        value: project
      - label: Título
        name: title
        widget: string
      - label: Informações técnicas
        name: tech_specs
        widget: list
        summary: "{{fields.info}}"
        minimize_collapsed: true
        field: {name: info, widget: string}
        required: false
      - label: Categoria
        name: category
        widget: select
        options:
          - Longas-metragens
          - Médias-metragens
          - Curtas-metragens
          - Coproduções
          - Séries
          - Origens
          - Distribuição
          - Coleções
          - Projetos
      - label: Trailer
        name: trailer
        widget: string
        required: false
        hint: >-
          O link para um vídeo do Vimeo.
      - label: Imagem de destaque
        name: image
        widget: image
      - label: Créditos da imagem de destaque
        name: image_credits
        widget: string
        required: false
      - label: Sinopse
        name: synopsis
        widget: markdown
      - label: Onde Assistir
        name: where_to_watch
        widget: list
        label_singular: "serviço"
        required: false
        fields:
          - label: Serviço
            name: title
            widget: string
          - label: Link
            name: url
            widget: string
      - label: Seções de conteúdo
        name: body
        widget: markdown
        required: false
        hint: >-
          Seções de conteúdo são separadas por uma linha horizontal (`***`). O título da seção é definido por um título de nível 2 (`##`).
      - label: Caminho original
        name: original_path
        widget: string
        required: false
        hint: >-
          O caminho original desse conteúdo no site antigo. Útil para criarmos um redirecionamento automático e evitarmos links quebrados no site.
