# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: main # Branch to update (master by default)

media_folder: "uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Resumo", name: "excerpt", widget: "text", required: false }
      - label: "Autor"
        name: "author"
        widget: "select"
        options:
          - { label: "Giba Assis Brasil", value: "giba" }
          - { label: "Jorge Furtado", value: "jorge" }
          - { label: "A Casa", value: "false" }
      - {
          label: "Data",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm:ss",
        }
      - { label: "Conteúdo", name: "body", widget: "markdown", required: false }
      - label: "Seção do Site"
        name: "category"
        widget: "select"
        options:
          - { label: "Blog", value: "blog" }
          - { label: "Notícias", value: "noticias" }
          - { label: "Textos", value: "links" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["news"]
    # PAGES
  # - name: "page"
  #   label: "Páginas"
  #   folder: "pages"
  #   sort: "title:asc"
  #   create: false
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
  #     - { label: "Title", name: "title", widget: "string", tagname: "h1" }
  #     - {
  #         label: "Meta Description",
  #         name: "meta_description",
  #         widget: "string",
  #         required: false,
  #       }
  #     - { label: "Permalink", name: "permalink", widget: "hidden" }
  #     - {
  #         label: "Section",
  #         name: "section",
  #         widget: "hidden",
  #         default: "{{name}}",
  #       }
  #     - {
  #         label: "Intro Paragraph",
  #         name: "intro_paragraph",
  #         widget: "markdown",
  #         required: false,
  #       }
  #     - { label: "Body", name: "body", widget: "markdown", required: false }
