# https://www.netlifycms.org/docs/configuration-options/
backend:
  name: github # Netlify’s Git Gateway connects to Git provider’s API
  repo: casacinepoa/casacinepoa.github.io
  branch: main # Branch to update (master by default)
  # site_domain: casacinepoa.com.br
  # auth_endpoint: auth
  # base_url: https://api.netlify.com
locale: pt
local_backend: true
media_folder: "uploads"
publish_mode: editorial_workflow
site_url: "https://www.casacinepoa.com.br/"
display_url: "https://www.casacinepoa.com.br/"
logo_url: "https://www.casacinepoa.com.br/assets/img/favicon.png"
# slug:
#   encoding: "unicode"
#   clean_accents: true
collections:
  - name: post
    label: Posts
    label_singular: Post
    folder: _posts
    sort: "date:asc"
    create: true
    delete: true
    extension: md
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/blog/{{year}}-{{month}}-{{day}}-{{slug}}/"
    summary: >-
      {{title}} ({{day}}/{{month}}/{{year}})
    description: >-
      Posts exibidos no Blog, com atribuição de autor, listas de tags e arquivos específicos.
    sortable_fields:
      - title
      - date
    view_filters:
      - label: "Posts da Ana"
        field: author
        pattern: "ana"
      - label: "Posts do Giba"
        field: author
        pattern: "giba"
      - label: "Posts do Jorge"
        field: author
        pattern: "jorge"
      - label: "Posts da Nora"
        field: author
        pattern: "nora"
    view_groups:
      - label: Rascunhos
        field: draft
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: "post"
      - label: Título
        name: title
        widget: string
      - label: Conteúdo
        name: body
        widget: markdown
      - label: Resumo
        name: excerpt
        widget: text
        required: false
        hint: >-
          Exibido na lista de posts do blog. Se deixar em branco, o site tentará gerar um resumo automaticamente a partir do primeiro parágrafo do post. Use até 240 caracteres para exibir o resumo inteiro.
      - label: Autor
        name: author
        widget: select
        options:
          - label: A Casa
            value: casa
          - label: Ana Luíza Azevedo
            value: ana
          - label: Giba Assis Brasil
            value: giba
          - label: Jorge Furtado
            value: jorge
          - label: Nora Goulart
            value: nora
      - label: Data
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss"
      - label: Tags
        name: tags
        widget: list
        required: false
        hint: >-
          Uma lista de tópicos separados por vírgulas. Se adicionadas, a notícia aperecerá na página de posts com essa tag.
      - label: Caminho original
        name: redirect_from
        default: null
        widget: string
        required: false
        hint: >-
          O caminho original desse conteúdo no site antigo. Útil para criarmos um redirecionamento automático e evitarmos links quebrados no site.
  - name: page
    label: Páginas
    label_singular: Página
    folder: _pages
    sort: "title:desc"
    create: true
    delete: true
    extension: md
    slug: "{{slug}}"
    preview_path: "/{{slug}}/"
    summary: >-
      {{title}}
    description: >-
      Páginas de conteúdo estático.
    sortable_fields:
      - title
    view_groups:
      - label: Rascunhos
        field: draft
    fields:
      - label: Título
        name: title
        widget: string
      - label: Conteúdo
        name: body
        widget: markdown
        required: false
      - label: Link permanente
        name: permalink
        required: false
        widget: string
        hint: >-
          O caminho da URL dessa página. Vai ser acessável em `casacinepoa.com.br/[LINK PERMANENTE]/`.
      - label: Imagem em Destaque
        name: image
        widget: image
        required: false
      - label: Legenda da imagem em destaque
        name: image_caption
        widget: string
        required: false
      - label: Resumo
        name: excerpt
        widget: text
        required: false
        hint: >-
          Exibido em resultados de busca. Se deixar em branco, o site tentará gerar um resumo automaticamente a partir do primeiro parágrafo do post. Use até 160 caracteres para exibir o resumo inteiro.
      - label: Caminho original
        name: redirect_from
        default: null
        widget: string
        required: false
        hint: >-
          O caminho original desse conteúdo no site antigo. Útil para criarmos um redirecionamento automático e evitarmos links quebrados no site.
      - label: Layout
        name: layout
        widget: select
        default: "page"
        options:
        - label: Sem layout
          value: default
        - label: Página simples
          value: page
        - label: Página "Sobre"
          value: about
        - label: Página de arquivo
          value: archive
        - label: Página de contato
          value: contact
        - label: Post de blog
          value: post
        - label: Página de projeto
          value: project
        - label: Lista de filmes
          value: lists/films
        - label: Lista de posts
          value: lists/posts
        - label: Lista de projetos
          value: lists/projects
        - label: Blog
          value: blog
        - label: Autor do blog
          value: author
  - name: news
    label: Notícias
    label_singular: Notícia
    description: >-
      As notícias são posts exibidos sem atribuição de autor na página de Notícias da Casa.
    folder: _news
    sort: "date:desc"
    create: true
    delete: true
    summary: >-
      {{title}} ({{day}}/{{month}}/{{year}})
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/noticias/{{year}}-{{month}}-{{day}}-{{slug}}/"
    view_groups:
      - label: Rascunhos
        field: draft
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Título
        name: title
        widget: string
      - label: Conteúdo
        name: body
        widget: markdown
      - label: Data
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss"
      - label: Tags
        name: tags
        widget: list
        required: false
        hint: >-
          Uma lista de tópicos separados por vírgulas. Se adicionadas, a notícia aperecerá na página de posts com essa tag.
      - label: Caminho original
        name: redirect_from
        widget: string
        required: false
        default: null
        hint: >-
          O caminho original desse conteúdo no site antigo. Útil para criarmos um redirecionamento automático e evitarmos links quebrados no site.
  - name: essays
    label: Textos
    label_singular: Texto
    folder: _essays
    sort: "date:desc"
    create: true
    delete: true
    summary: >-
      {{title}} ({{day}}/{{month}}/{{year}})
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/textos/{{year}}-{{month}}-{{day}}-{{slug}}/"
    description: >-
      Textos são posts exibidos na página de Textos, com sua própria listagem e organização.
    view_groups:
      - label: Rascunhos
        field: draft
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Título
        name: title
        widget: string
      - label: Conteúdo
        name: body
        widget: markdown
      - label: Autor
        name: author
        widget: hidden
        default: casa
      - label: Categoria
        name: category
        widget: select
        options:
          - label: Textos sobre Cinema
            value: Textos sobre Cinema
          - label: Roteiros
            value: Roteiros
      - label: Arquivo
        name: file
        widget: file
        required: false
        media_library:
          config:
            allow_multiple: false
            media_folder: "/uploads/roteiros/"
      - label: Date
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss"
      - label: Caminho original
        name: redirect_from
        default: null
        widget: string
        required: false
        hint: >-
          O caminho original desse conteúdo no site antigo. Útil para criarmos um redirecionamento automático e evitarmos links quebrados no site.
  - name: projects
    label: Filmes
    label_singular: Filme
    folder: _projects
    sort: "title:desc"
    create: true
    delete: true
    slug: "{{slug}}"
    preview_path: "/filmes/{{slug}}"
    editor:
      preview: false
    view_filters:
    - label: "Longas"
      field: category
      pattern: "Longas-metragens"
    - label: "Coproduções"
      field: category
      pattern: "Coproduções"
    - label: "Médias"
      field: category
      pattern: "Médias-metragens"
    - label: "Curtas"
      field: category
      pattern: "Curtas-metragens"
    - label: "Séries"
      field: category
      pattern: "Séries"
    - label: "Origens"
      field: category
      pattern: "Origens"
    - label: "Distribuição"
      field: category
      pattern: "Distribuição"
    - label: "Coleções"
      field: category
      pattern: "Coleções"
    - label: "Projetos"
      field: category
      pattern: "Projetos"
    - label: "Episódios"
      field: category
      pattern: "Episódios"
    description: >-
      Os projetos ou os filmes. Dependendo da categoria, eles são exibidos em sua lista respectiva.
    fields:
      - label: Layout
        name: layout
        widget: hidden
        value: project
      - label: Título
        name: title
        widget: string
      - label: Informações técnicas
        name: tech_specs
        widget: list
        summary: "{{fields.info}}"
        minimize_collapsed: true
        field: {name: info, widget: string}
        required: false
      - label: Categoria
        name: category
        widget: select
        options:
          - Longas-metragens
          - Médias-metragens
          - Curtas-metragens
          - Coproduções
          - Séries
          - Origens
          - Distribuição
          - Coleções
          - Projetos
          - Episódios
      - label: Trailer
        name: trailer
        widget: string
        required: false
        hint: >-
          O link para um vídeo do Vimeo.
      - label: Imagem de destaque
        name: image
        widget: image
      - label: Créditos da imagem de destaque
        name: image_credits
        widget: string
        required: false
      - label: Sinopse
        name: body
        widget: markdown
      - label: Onde Assistir
        name: where_to_watch
        widget: list
        label_singular: "serviço"
        required: false
        fields:
          - label: Serviço
            name: title
            widget: string
          - label: Link
            name: url
            widget: string
      - label: Detalhes
        name: details
        widget: list
        summary: "{{fields.title}}"
        required: false
        fields:
          - label: Título
            name: title
            widget: string
          - label: Conteúdo
            name: content
            widget: markdown
      - label: Caminho original
        name: redirect_from
        default: null
        widget: string
        required: false
        hint: >-
          O caminho original desse conteúdo no site antigo. Útil para criarmos um redirecionamento automático e evitarmos links quebrados no site.
  - name: menu
    label: Menus
    label_singular: Menu
    description: >-
      Os menus de navegação do site.
    create: false
    delete: false
    editor:
      preview: false
    files:
      - label: Menu Principal
        file: _data/menus/main.yml
        name: main
        fields:
          - label: Itens
            widget: list
            name: items
            label_singular: "item"
            fields:
              - label: Rótulo
                name: title
                widget: string
              - label: Link
                name: url
                widget: relation
                collection: "page"
                display_fields: ["{{title}} - {{permalink}}"]
                search_fields:
                  - title
                value_field: permalink
              - label: Link externo
                name: required
                widget: boolean
                hint: >-
                  Se ativo, abrirá o link em uma nova janela.
      - label: Menu das páginas Sobre
        file: _data/menus/about.yml
        name: about
        description: >-
          Os menus de navegação do site.
        fields:
          - label: Itens
            widget: list
            name: items
            label_singular: "item"
            fields:
              - label: Rótulo
                name: title
                widget: string
              - label: Link
                name: url
                widget: relation
                collection: "page"
                display_fields: ["{{title}} - {{permalink}}"]
                search_fields:
                  - title
                value_field: permalink
              - label: Link externo
                name: required
                required: false
                widget: boolean
                hint: >-
                  Se ativo, abrirá o link em uma nova janela.
  - name: banner
    label: Banners
    label_singular: Banner
    folder: _banners
    sort: "date:desc"
    create: true
    delete: true
    publish: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    description: >-
      Banners exibidos no início e no fim da página inicial. Apenas os dois banners mais recentes serão exibidos.
    fields:
      - label: Data de ativação
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss"
        required: true
      - label: Imagem
        name: image
        widget: image
        allow_multiple: false
        required: true
      - label: Título
        name: title
        widget: string
      - label: Conteúdo
        name: body
        widget: markdown
      - label: URL de destino
        name: link
        widget: string
        required: true
  - name: people
    label: Pessoas
    label_singular: Pessoa
    folder: _people
    sort: "title:asc"
    create: true
    delete: true
    editor:
      preview: false
    slug: "{{slug}}"
    description: >-
      As pessoas envolvidas na Casa, sejam os sócios, funcionários, equipe e elenco.
    view_filters:
    - label: "Sócios"
      field: category
      pattern: "socios"
    - label: "Funcionários"
      field: category
      pattern: "funcionarios"
    - label: "Equipes"
      field: category
      pattern: "equipes"
    - label: "Elencos"
      field: category
      pattern: "elencos"
    - label: "Ex-Sócios"
      field: category
      pattern: "passado"
    fields:
      - label: Nome
        name: title
        widget: string
      - label: Foto
        name: image
        widget: image
        required: false
      - label: Função
        name: role
        widget: string
        required: false
      - label: Bio
        name: body
        widget: markdown
        required: false
      - label: Currículo
        name: cv
        widget: markdown
        required: false
      - label: Aparições
        name: order
        widget: number
        required: false
        hint: >-
          Útil para a página de Colaboradores, vai ordenar automaticamente a lista de colaboradores frequentes em Equipe e Elenco.
      - label: Links
        name: links
        widget: list
        label_singular: "link"
        required: false
        fields:
          - label: Rótulo
            name: title
            widget: string
          - label: URL de destino
            name: url
            widget: string
      - label: Categoria
        name: category
        widget: select
        options:
          - label: Sócios
            value: socios
          - label: Funcionários
            value: funcionarios
          - label: Equipes
            value: equipes
          - label: Elencos
            value: elencos
          - label: Ex-Sócios
            value: passado
